Repository codeit-bootcamp-frontend/11-Sprint-Mission, pull requests merged in 2024-09, with the labels that each got.

#25 [한승지] Sprint1
  assets/icon/footer_ic_facebook.png
  assets/icon/footer_ic_instagram.png
  assets/icon/footer_ic_twitter.png
  assets/icon/footer_ic_youtube.png
  assets/images/bottom_banner_image.png
  assets/images/header_logo.png
  assets/images/infomation_image1.png
  assets/images/infomation_image2.png
  assets/images/infomation_image3.png
  assets/images/top_banner_image.png
  index.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  style.css
Labels: 매운맛🔥

#16 [김용철]Sprint1
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  style.css
  판다 얼굴.png
Labels: 매운맛🔥

#23 [김예도] Sprint1
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/button/login/login.png
  img/button/show/show.png
  img/card/Img_home_01.png
  img/card/Img_home_02.png
  img/card/Img_home_03.png
  img/icon/ic_facebook@3x.png
  img/icon/ic_instagram@3x.png
  img/icon/ic_twitter@3x.png
  img/icon/ic_youtube@3x.png
  img/logo/logo.png
  index.html
  style.css
Labels: 매운맛🔥

#44 [홍지윤] Sprint 1
  코드잇 스프린트 미션 1/faq.html
  코드잇 스프린트 미션 1/image/contents/Img_home_01.png
  코드잇 스프린트 미션 1/image/contents/Img_home_02.png
  코드잇 스프린트 미션 1/image/contents/Img_home_03.png
  코드잇 스프린트 미션 1/image/contents/Img_home_bottom.png
  코드잇 스프린트 미션 1/image/contents/Img_home_top.png
  코드잇 스프린트 미션 1/image/logo/Property 1=sm.png
  코드잇 스프린트 미션 1/image/logo/favicon-16x16.png
  코드잇 스프린트 미션 1/image/sns/ic_facebook.png
  코드잇 스프린트 미션 1/image/sns/ic_instagram.png
  코드잇 스프린트 미션 1/image/sns/ic_twitter.png
  코드잇 스프린트 미션 1/image/sns/ic_youtube.png
  코드잇 스프린트 미션 1/index.css
  코드잇 스프린트 미션 1/index.html
  코드잇 스프린트 미션 1/items.html
  코드잇 스프린트 미션 1/login.html
  코드잇 스프린트 미션 1/privacy.html
Labels: 매운맛🔥, 미완성🫠

#27 [오병훈] Sprint 2
  sprint-mission-1/faq.html
  sprint-mission-1/images/home/Img_home_01.png
  sprint-mission-1/images/home/Img_home_02.png
  sprint-mission-1/images/home/Img_home_03.png
  sprint-mission-1/images/home/Img_home_bottom.png
  sprint-mission-1/images/home/Img_home_top.png
  sprint-mission-1/images/icon/Component 2.png
  sprint-mission-1/images/icon/Component 3.png
  sprint-mission-1/images/icon/btn_visibility_on_24px.png
  sprint-mission-1/images/icon/ic_facebook.png
  sprint-mission-1/images/icon/ic_instagram.png
  sprint-mission-1/images/icon/ic_twitter.png
  sprint-mission-1/images/icon/ic_youtube.png
  sprint-mission-1/images/logo/Property 1=sm.png
  sprint-mission-1/images/logo/Property 1=sm@2x.png
  sprint-mission-1/images/logo/Property 1=sm@3x.png
  sprint-mission-1/index.html
  sprint-mission-1/items.html
  sprint-mission-1/login.html
  sprint-mission-1/privacy.html
  sprint-mission-1/signup.html
  sprint-mission-1/style/home.css
  sprint-mission-1/style/login.css
Labels: 매운맛🔥

#22 [박연학] Sprint2
  faq.html
  images/logos/blind.png
  images/logos/favicon.ico
  images/logos/panda.png
  images/logos/see.png
  images/main/check.png
  images/main/end.png
  images/main/main.png
  images/main/register.png
  images/main/search.png
  images/social/facebook.svg
  images/social/google.png
  images/social/instagram.svg
  images/social/kakao.png
  images/social/twitter.svg
  images/social/youtube.svg
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  style/global.css
  style/index.css
  style/sign.css
Labels: 순한맛🐑

#2 [신휘철] Sprint1
  css/common.css
  css/layout.css
  css/main.css
  css/style.css
  css/sub.css
  faq.html
  images/Img_home_01.svg
  images/Img_home_02.svg
  images/Img_home_03.svg
  images/Img_home_bottom.svg
  images/Img_home_top.svg
  images/facebook_icon.svg
  images/index.JPG
  images/instagram_icon.svg
  images/logo.svg
  images/twitter_icon.svg
  images/youtube_icon.svg
  index.html
  items.html
  login.html
  privacy.html
  스프린트 1 미션.md
Labels: 매운맛🔥

#14 [민지이] sprint2
  .DS_Store
  faq.html
  home.css
  img/.DS_Store
  img/Img-home-bottom.png
  img/Img-home-top.png
  img/Img-hot-item.png
  img/Img-register.png
  img/Img-search.png
  img/home-logo.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_instagram.png
  img/ic_kakao.png
  img/ic_twitter.png
  img/ic_visibility_on.png
  img/ic_youtube.png
  img/logo.png
  index.html
  login.css
  login.html
  privacy.html
  signup.css
  signup.html
  trade-item.html
Labels: 매운맛🔥

#4 [양정화] Sprint1
  .DS_Store
  assets/.DS_Store
  assets/css/common.css
  assets/css/main-copy.css
  assets/css/main.css
  assets/css/reset.css
  assets/css/variable.css
  assets/fonts/.DS_Store
  assets/fonts/otf/.DS_Store
  assets/fonts/otf/Pretendard-Bold.otf
  assets/fonts/otf/Pretendard-Medium.otf
  assets/fonts/otf/Pretendard-Regular.otf
  assets/fonts/otf/Pretendard-SemiBold.otf
  assets/fonts/ttf/.DS_Store
  assets/fonts/ttf/Pretendard-Bold.ttf
  assets/fonts/ttf/Pretendard-Medium.ttf
  assets/fonts/ttf/Pretendard-Regular.ttf
  assets/fonts/ttf/Pretendard-SemiBold.ttf
  assets/fonts/woff/.DS_Store
  assets/fonts/woff/Pretendard-Bold.woff
  assets/fonts/woff/Pretendard-Medium.woff
  assets/fonts/woff/Pretendard-Regular.woff
  assets/fonts/woff/Pretendard-SemiBold.woff
  assets/fonts/woff2/.DS_Store
  assets/fonts/woff2/Pretendard-Bold.woff2
  assets/fonts/woff2/Pretendard-Medium.woff2
  assets/fonts/woff2/Pretendard-Regular.woff2
  assets/fonts/woff2/Pretendard-SemiBold.woff2
  assets/images/.DS_Store
  assets/images/Img_home_01.png
  assets/images/Img_home_02.png
  assets/images/Img_home_03.png
  assets/images/Img_home_bottom.png
  assets/images/Img_home_top.png
  assets/images/ic_facebook.png
  assets/images/ic_instagram.png
  assets/images/ic_twitter.png
  assets/images/ic_youtube.png
  assets/images/logo.png
  assets/images/mobiles/logo.png
  assets/images/tablets/.DS_Store
  assets/images/tablets/Img_home_01.png
  assets/images/tablets/Img_home_02.png
  assets/images/tablets/Img_home_03.png
  index.html
Labels: 매운맛🔥

#38 [이주훈]Sprint1
  sprint1/css/style.css
  sprint1/faq.html
  sprint1/img/.DS_Store
  sprint1/img/home/bottom-banner-image.png
  sprint1/img/home/feature1-image.png
  sprint1/img/home/feature2-image.png
  sprint1/img/home/feature3-image.png
  sprint1/img/home/hero-image.png
  sprint1/img/logo/favicon.ico
  sprint1/img/logo/panda-market-logo.png
  sprint1/img/social/facebook-logo.svg
  sprint1/img/social/instagram-logo.svg
  sprint1/img/social/twitter-logo.svg
  sprint1/img/social/youtube-logo.svg
  sprint1/index.html
  sprint1/item.html
  sprint1/login.html
  sprint1/privacy.html
Labels: 미완성🫠, 순한맛🐑

#15 [임광조] Sprint11
  README.md
  faq.html
  image/Img_home_bottom.png
  image/feature1-image.png
  image/feature2-image.png
  image/feature3-image.png
  image/hero-image.png
  index.html
  items.html
  login.html
  privacy.html
  styles.css
Labels: 매운맛🔥

#3 [우재현] Sprint1
  .github/pull_request_template.md
  README.md
  faq/index.html
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  public/fonts/ROKAF_Sans/ROKAF Sans Bold.ttf
  public/fonts/ROKAF_Sans/ROKAF Sans Medium.ttf
  public/images/Img_home_01.png
  public/images/Img_home_01@2x.png
  public/images/Img_home_01@3x.png
  public/images/Img_home_02.png
  public/images/Img_home_02@2x.png
  public/images/Img_home_02@3x.png
  public/images/Img_home_03.png
  public/images/Img_home_03@2x.png
  public/images/Img_home_03@3x.png
  public/images/Img_home_bottom.png
  public/images/Img_home_top.png
  public/images/logo_icon.png
  public/images/sprint_mission_1_screencapture.png
  style.css
Labels: 매운맛🔥

#17 [이동훈] Sprint1
  imges/contents/Img_home_01.png
  imges/contents/Img_home_02.png
  imges/contents/Img_home_03.png
  imges/contents/Img_home_bottom.png
  imges/contents/Img_home_top.png
  imges/icons/ic_facebook.png
  imges/icons/ic_instagram.png
  imges/icons/ic_twitter.png
  imges/icons/ic_youtube.png
  imges/logos/logo.png
  imges/logos/panda-face.png
  index.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  styles/main.css
Labels: 매운맛🔥

#28 [박종찬] sprint1
  Test.txt
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/facebook.png
  img/first.png
  img/instar.png
  img/twitter.png
  img/youtube.png
  img/마지막 그림.png
  img/배경.png
  img/판다마켓.png
  img/판다얼굴.png
  index.html
  style.css
Labels: 매운맛🔥

#34 [한정빈] Sprint1
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  faq.html
  ic_facebook.svg
  ic_instagram.svg
  ic_twitter.svg
  ic_youtube.svg
  index.html
  items.html
  login.html
  logo.png
  privacy.html
  style.css
Labels: 매운맛🔥

#32 [김진희] Sprint1
  ROKAF Sans Bold.ttf
  ROKAF Sans Medium.ttf
  faq.html
  images/home_01.png
  images/home_02.png
  images/home_03.png
  images/home_bottom.png
  images/home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  items.html
  login.html
  panda_market.css
  panda_market.html
  privacy.html
Labels: 순한맛🐑

#6 [강수민] Sprint1
  assets/images/icons/ic_facebook.png
  assets/images/icons/ic_instagram.png
  assets/images/icons/ic_twitter.png
  assets/images/icons/ic_youtube.png
  assets/images/img_home_01.png
  assets/images/img_home_02.png
  assets/images/img_home_03.png
  assets/images/img_home_bottom.png
  assets/images/img_home_top.png
  assets/images/logo.png
  assets/style/style.css
  index.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
Labels: 매운맛🔥

#24 [김관호] Sprint1
  faq.html
  imgs/ic_facebook.png
  imgs/ic_instagram.png
  imgs/ic_twitter.png
  imgs/ic_youtube.png
  imgs/main-1.png
  imgs/main-2.png
  imgs/main-3.png
  imgs/main-4.png
  imgs/main-5.png
  imgs/panda_icon.png
  imgs/panda_icon_sm1.png
  index.html
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#8 [원서연] Sprint1
  sprint_mission_1/.vscode/settings.json
  sprint_mission_1/faq.html
  sprint_mission_1/icon/Group.png
  sprint_mission_1/icon/ic_instagram.png
  sprint_mission_1/icon/ic_twitter.png
  sprint_mission_1/icon/ic_youtube.png
  sprint_mission_1/img/Img_home_01.png
  sprint_mission_1/img/Img_home_02.png
  sprint_mission_1/img/Img_home_03.png
  sprint_mission_1/img/Img_home_bottom.png
  sprint_mission_1/img/Img_home_top.png
  sprint_mission_1/img/판다 얼굴.png
  sprint_mission_1/img/판다마켓.png
  sprint_mission_1/index.html
  sprint_mission_1/items.html
  sprint_mission_1/login.html
  sprint_mission_1/privacy.html
  sprint_mission_1/style.css
Labels: 매운맛🔥

#9 [김도훈] Sprint1
  Sprint-Mission1/.vscode/settings.json
  Sprint-Mission1/css/font.css
  Sprint-Mission1/css/style.css
  Sprint-Mission1/faq.html
  Sprint-Mission1/images/icons/google.png
  Sprint-Mission1/images/icons/ic_facebook.png
  Sprint-Mission1/images/icons/ic_instagram.png
  Sprint-Mission1/images/icons/ic_twitter.png
  Sprint-Mission1/images/icons/ic_youtube.png
  Sprint-Mission1/images/icons/kakao.png
  Sprint-Mission1/images/icons/visibility.png
  Sprint-Mission1/images/icons/visible.png
  Sprint-Mission1/images/logo/logo.png
  Sprint-Mission1/images/logo/logo_face.png
  Sprint-Mission1/images/logo/logo_txt.png
  Sprint-Mission1/images/main/Img_home_01.png
  Sprint-Mission1/images/main/Img_home_02.png
  Sprint-Mission1/images/main/Img_home_03.png
  Sprint-Mission1/images/main/Img_home_bottom.png
  Sprint-Mission1/images/main/Img_home_top.png
  Sprint-Mission1/index.html
  Sprint-Mission1/items.html
  Sprint-Mission1/login.html
  Sprint-Mission1/privacy.html
  Sprint-Mission1/signup.html
Labels: 매운맛🔥

#36 [조영선] Sprint1
  Group (1).png
  Group.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Vector.png
  ic_instagram.png
  mission1-2.css
  mission1-2.html
  판다 얼굴.png
Labels: 매운맛🔥, 미완성🫠

#10 [서현우] Sprint1
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/Property 1=lg.png
  img/btn_large.png
  img/btn_small_48.png
  img/icon_facebook.png
  img/icon_instagram.png
  img/icon_twitter.png
  img/icon_youtube.png
  img/©codeit - 2024.png
  index.css
  index.html
  reset.css
Labels: 매운맛🔥, 미완성🫠

#26 [이준희] sprint1
  Component 2.png
  Component 3.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Property 1=lg.png
  btn_visibility_on_24px.png
  faq.html
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  items.html
  login.html
  pandamarket.html
  privacy.html
  signup.html
  style.css
Labels: 매운맛🔥

#5 [이학수] Sprint1
  faq.html
  favicon.png
  img/bg-bottom.png
  img/bg-hero.png
  img/hot-item.png
  img/ico-facebook.png
  img/ico-instagram.png
  img/ico-twitter.png
  img/ico-youtube.png
  img/logo.png
  img/register.png
  img/search.png
  img/site-name.png
  index.html
  items.html
  login.html
  privacy.html
  readme.md
  style.css
Labels: 매운맛🔥

#12 [정소망] sprint1
  faq.html
  img/ic_facebook.svg
  img/ic_instagram.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/info1.svg
  img/info2.svg
  img/info3.svg
  img/logo-title.svg
  img/logo.svg
  img/outside-bottom.svg
  img/outside-top.svg
  index.css
  index.html
  items.html
  login.html
  privacy.html
Labels: 순한맛🐑

#31 [강시호] Sprint1
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Img_home_top1.png
  faq
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  items
  login
  logo.png
  privacy
  prj1_practice.html
  style1.css
Labels: 미완성🫠, 순한맛🐑

#48 [전정민] Sprint1
  .DS_Store
  css/reset.css
  css/style.css
  faq.html
  images/.DS_Store
  images/landing/Img_home_01.png
  images/landing/Img_home_02.png
  images/landing/Img_home_03.png
  images/landing/Img_home_bottom.png
  images/landing/Img_home_top.png
  images/logo/logo.png
  images/social/ic_facebook.png
  images/social/ic_instagram.png
  images/social/ic_twitter.png
  images/social/ic_youtube.png
  index.html
  items.html
  login.html
  privacy.html
Labels: 순한맛🐑

#52 [김태완] Sprint1
  .vscode/settings.json
  CSS/index.css
  faq.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Property 1=lg.png
  image/gnb/Vector.png
  image/gnb/ic_facebook.png
  image/gnb/ic_instagram.png
  image/gnb/ic_youtube.png
  image/gnb/standard=pc.png
  image/img/landing/desktop_01.png
  image/img/landing/desktop_05.png
  index.html
  items.html
  login.html
  privacy.html
Labels: 매운맛🔥, 미완성🫠

#84 [홍지윤] sprint2
  desktop.ini
  text.txt
  코드잇 스프린트 미션/faq.html
  코드잇 스프린트 미션/home.html
  코드잇 스프린트 미션/image/contents/Img_home_01.png
  코드잇 스프린트 미션/image/contents/Img_home_02.png
  코드잇 스프린트 미션/image/contents/Img_home_03.png
  코드잇 스프린트 미션/image/contents/Img_home_bottom.png
  코드잇 스프린트 미션/image/contents/Img_home_top.png
  코드잇 스프린트 미션/image/icon/eye-close.png
  코드잇 스프린트 미션/image/logo/Property 1=sm.png
  코드잇 스프린트 미션/image/logo/favicon-16x16.png
  코드잇 스프린트 미션/image/logo/login-logo.png
  코드잇 스프린트 미션/image/sns/ic.google.png
  코드잇 스프린트 미션/image/sns/ic_facebook.png
  코드잇 스프린트 미션/image/sns/ic_instagram.png
  코드잇 스프린트 미션/image/sns/ic_kakao.png
  코드잇 스프린트 미션/image/sns/ic_twitter.png
  코드잇 스프린트 미션/image/sns/ic_youtube.png
  코드잇 스프린트 미션/items.html
  코드잇 스프린트 미션/login.html
  코드잇 스프린트 미션/privacy.html
  코드잇 스프린트 미션/signup.html
  코드잇 스프린트 미션/style/global.css
  코드잇 스프린트 미션/style/home.css
  코드잇 스프린트 미션/style/login.css
  코드잇 스프린트 미션/style/signup.css
Labels: 매운맛🔥

#60 [김진희] Sprint 2
  _redirects
  images/favicon.ico
  images/google.png
  images/kakao.png
  images/medium-logo.png
  index.html
  panda_market.html
  site.html/faq.html
  site.html/items.html
  site.html/login.html
  site.html/privacy.html
  site.html/signup.html
  style.css/common.css
  style.css/login,signup-common.css
  style.css/login.css
  style.css/panda_market.css
  style.css/signup.css
Labels: 매운맛🔥

#75 [박종찬] Sprint2
  Test.txt
  css/color.css
  css/reset.css
  css/style.css
  font/ROKAF Sans Bold.ttf
  img/Component 2@2x.png
  img/Component 2@3x.png
  img/Component 3@2x.png
  img/Component 3@3x.png
  img/close-eye.png
  img/google-logo.png
  img/kakao-logo.png
  img/open-eye.png
  img/스프린트 미션 (1).zip
  img/스프린트 미션 (2).zip
  img/스프린트 미션 (3).zip
  img/스프린트 미션.zip
  img/판다 얼굴103.png
  index.html
  login/css/style.css
  login/index.html
  login/signup/index.html
Labels: 매운맛🔥

#72 [석지우] Sprint2
  img/input-icon/eye-off.png
  img/login-icon/google.png
  img/login-icon/kakaotalk.png
  index.html
  login
  login.html
  loginStyle.css
  signup.html
  signupStyle.css
  style.css
Labels: 매운맛🔥

#53 [김용철] Sprint2
  .github/Component 2.png
  .github/Component 3.png
  .github/Img_home_01.png
  .github/Img_home_02.png
  .github/Img_home_03.png
  .github/Img_home_bottom (1).png
  .github/Img_home_top.png
  .github/Vector.png
  .github/ic_facebook.png
  .github/ic_instagram.png
  .github/ic_twitter.png
  .github/ic_youtube.png
  .github/index.html
  .github/loginstyle.css
  .github/signup.css
  .github/style.css
  .github/판다 얼굴.png
  .github/판다.html
  .github/회원가입.html
Labels: 매운맛🔥

#63 [김예도] Sprint2
  img/icon/google.png
  img/icon/ic_visibility_off.png
  img/icon/ic_visibility_on.png
  img/icon/kakao.png
  index.html
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#49 [우재현] Sprint2
  .github/pull_request_template.md
  README.md
  index.html
  login/index.html
  public/css/index.css
  public/css/login.css
  public/css/style.css
  public/images/Img_home_01@2x.png
  public/images/Img_home_01@3x.png
  public/images/Img_home_02@2x.png
  public/images/Img_home_02@3x.png
  public/images/Img_home_03@2x.png
  public/images/Img_home_03@3x.png
  public/images/icon/Component 2.png
  public/images/icon/Component 3.png
  public/images/icon/btn_visibility_off.png
  public/images/icon/btn_visibility_on.png
  public/images/icon/ic_facebook.png
  public/images/icon/ic_instagram.png
  public/images/icon/ic_twitter.png
  public/images/icon/ic_youtube.png
  public/images/logo_icon_high.png
  public/images/sprint_mission_1_screencapture.png
  public/js/login.js
  public/js/signup.js
  views/faq.html
  views/items.html
  views/login.html
  views/privacy.html
  views/signup.html
Labels: 매운맛🔥

#57 [양정화] sprint2
  .DS_Store
  .gitignore
  assets/.DS_Store
  assets/css/common.css
  assets/css/main-copy.css
  assets/css/main.css
  assets/css/reset.css
  assets/css/user.css
  assets/fonts/.DS_Store
  assets/fonts/otf/.DS_Store
  assets/fonts/ttf/.DS_Store
  assets/fonts/woff/.DS_Store
  assets/fonts/woff2/.DS_Store
  assets/images/.DS_Store
  assets/images/icon-eye-close.png
  assets/images/icon-eye-open.png
  assets/images/icon-google.png
  assets/images/icon-kakao.png
  assets/images/tablets/.DS_Store
  assets/js/common.js
  assets/js/user.js
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#59 [최주영] Sprint2
  css/index.css
  css/login.css
  css/style.css
  images/index/facebook.png
  images/index/favicon.ico
  images/index/hot-item.png
  images/index/instagram.png
  images/index/logo.png
  images/index/outro.png
  images/index/register.png
  images/index/search.png
  images/index/twitter.png
  images/index/visual.png
  images/index/youtube.png
  images/login/btn_visibility_off.png
  images/login/btn_visibility_on.png
  images/login/google.png
  images/login/kakao.png
  images/login/logo.png
  index.html
  login.html
  signup.html
  styles.css
Labels: 매운맛🔥

#69 [이준희] Sprint2
  index.html
  login.html
  pandamarket.html
  signup.html
  style.css
  style2.css
  style3.css
Labels: 매운맛🔥

#74 Basic 김관호 sprint2
  11-Sprint-Mission-1/.github/items.html
  11-Sprint-Mission-1/.github/pull_request_template.md
  11-Sprint-Mission-1/.github/workflows/delete-merged-branch-config.yml
  11-Sprint-Mission-1/faq.html
  11-Sprint-Mission-1/imgs/ic_facebook.png
  11-Sprint-Mission-1/imgs/ic_instagram.png
  11-Sprint-Mission-1/imgs/ic_twitter.png
  11-Sprint-Mission-1/imgs/ic_youtube.png
  11-Sprint-Mission-1/imgs/main-1.png
  11-Sprint-Mission-1/imgs/main-2.png
  11-Sprint-Mission-1/imgs/main-3.png
  11-Sprint-Mission-1/imgs/main-4.png
  11-Sprint-Mission-1/imgs/main-5.png
  11-Sprint-Mission-1/imgs/panda_icon.png
  11-Sprint-Mission-1/imgs/panda_icon_sm1.png
  11-Sprint-Mission-1/index.html
  11-Sprint-Mission-1/login.html
  11-Sprint-Mission-1/privacy.html
  11-Sprint-Mission-1/style.css
  11-Sprint-Mission-2/imgs/google-icon.png
  11-Sprint-Mission-2/imgs/kakao-icon.png
  11-Sprint-Mission-2/imgs/panda-face.png
  11-Sprint-Mission-2/login.html
  11-Sprint-Mission-2/signup.html
  11-Sprint-Mission-2/style-login.css
  11-Sprint-Mission-2/style-signup.css
Labels: 매운맛🔥

#76 [김도훈] Sprint2
  Sprint-Mission1/css/style.css
  Sprint-Mission1/images/main/og_img.png
  Sprint-Mission1/index.html
Labels: 매운맛🔥

#80 [조영선] Sprint2
  Component 2.png
  Component 3.png
  btn_visibility_off_24px.png
  login.css
  login.html
  mission1-3.css
  mission1-3.html
  signup.css
  signup.html
  판다 얼굴.png
  판다마켓.png
Labels: 매운맛🔥

#82 [한승지] sprint2
  assets/icon/facebook_logo.png
  assets/icon/google_logo.png
  assets/icon/instagram_logo.png
  assets/icon/kakao_logo.png
  assets/icon/password_show.png
  assets/icon/twitter_logo.png
  assets/icon/youtube_logo.png
  assets/images/header_logo.png
  assets/images/panda_logo.png
  common/css/font.css
  common/css/global.css
  index.css
  index.html
  pages/faq/faq.html
  pages/items/items.html
  pages/login.html
  pages/login/login.css
  pages/login/login.html
  pages/privacy/privacy.html
  pages/signUp/signup.css
  pages/signUp/signup.html
Labels: 매운맛🔥

#77 [정소망] sprint2
  faq.html
  img/btn_visibility_off.svg
  img/btn_visibility_on.svg
  img/google-login.png
  img/kakao-login.png
  img/login-logo.svg
  index.html
  items.html
  js/login.js
  js/signup.js
  login.html
  privacy.html
  signup.html
  style/page/index.css
  style/page/index.css.map
  style/page/index.scss
  style/page/login.css
  style/page/login.css.map
  style/page/login.scss
  style/page/signup.css
  style/page/signup.css.map
  style/page/signup.scss
  style/setting/_fonts.scss
  style/setting/_reset.scss
  style/setting/_vars.scss
  style/style.css
  style/style.css.map
  style/style.scss
Labels: 순한맛🐑

#62 [오병훈]Sprint3
  sprint-mission-1/images/logo/preview_image.png
  sprint-mission-1/index.html
  sprint-mission-1/login.html
  sprint-mission-1/signup.html
  sprint-mission-1/style/home.css
  sprint-mission-1/style/login.css
Labels: 매운맛🔥

#73 [장수경] Sprint2
  .DS_Store
  common.css
  eyeo.svg
  eyex.svg
  google.png
  home.css
  index.html
  kakao.png
  sign.css
  signin.html
  signup.html
Labels: 매운맛🔥

#79 [민지이] sprin3
  common.css
  home.css
  index.css
  index.html
  login.css
  login.html
  signup.css
  signup.html
Labels: 매운맛🔥

#99 [김예도] Sprint3
  global.css
  img/logo/TagLogo.png
  index.html
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#101 [석지우] Sprint3
  index.html
  login.html
  loginStyle.css
  signup.html
  signupStyle.css
  style.css
Labels: 매운맛🔥

#111 Basic 한승지 sprint3
  index.css
  index.html
  pages/login/login.css
  pages/signUp/signup.css
Labels: 매운맛🔥

#86 [강수민] sprint3
  assets/images/home/img_home_01_mobile.png
  assets/images/home/img_home_01_tablet.png
  assets/images/home/img_home_02_mobile.png
  assets/images/home/img_home_02_tablet.png
  assets/images/home/img_home_03_mobile.png
  assets/images/home/img_home_03_tablet.png
  assets/images/home/logo_mobile.png
  index.html
  js/auth.js
  style/auth.css
  style/common.css
  style/style.css
Labels: 매운맛🔥

#94 [박종찬] sprint3
  css/style.css
  font/ROKAF-Sans-Bold.ttf
  index.html
  login/css/style.css
Labels: 매운맛🔥

#87 [양정화] sprint3
  assets/css/common.css
  assets/css/main.css
  assets/css/signup.css
  assets/css/user.css
  assets/images/img_landing.png
  assets/images/mobiles/logo.png
  assets/js/common.js
  assets/js/components/headerTemplate.js
  assets/js/pages/main.js
  assets/js/pages/user.js
  assets/js/user.js
  assets/js/utils/domReady.js
  assets/js/utils/formValidation.js
  assets/js/utils/passwordToggle.js
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#90 [원서연] sprint3
  sprint_mission_1/common.css
  sprint_mission_1/img/메타태그 이미지.png
  sprint_mission_1/index.css
  sprint_mission_1/index.html
  sprint_mission_1/login.css
  sprint_mission_1/signup.css
Labels: 매운맛🔥

#100 [윤예지] Sprint3
  css/auth.css
  css/common.css
  css/main.css
  css/primary.css
  css/user.css
  images/logo.png
  index.html
  pages/login.html
  pages/signup.html
Labels: 매운맛🔥

#106 [이동훈] Sprint3
  README.md
  images/fandamarket-og.png
  images/logos/Frame 2609444.svg
  index.html
  pages/login.html
  pages/signup.html
  styles/auth.css
  styles/main.css
Labels: 매운맛🔥

#108 [김진희] Sprint3
  .vscode/settings.json
  _redirects
  images/google.png
  images/google.svg
  images/ic_facebook.png
  images/ic_facebook.svg
  images/ic_instagram.png
  images/ic_instagram.svg
  images/ic_twitter.png
  images/ic_twitter.svg
  images/ic_youtube.png
  images/ic_youtube.svg
  images/kakao.png
  images/kakao.svg
  images/medium-logo.svg
  index.html
  site.html/login.html
  site.html/signup.html
  style.css/common.css
  style.css/form-style.css
  style.css/login,signup-common.css
  style.css/login.css
  style.css/panda_market.css
  style.css/signup.css
Labels: 매운맛🔥

#91 [신휘철] Sprint3
  css/layout.css
  css/main.css
  css/sub.css
  images/logo-m.svg
  images/ogImage.png
  index.html
  js/login.js
  login.html
  스프린트 2 미션.md
  스프린트 3 미션.md
Labels: 매운맛🔥

#114 [이준희] Sprint3
  index.html
  login.html
  signup.html
  style_index.css
  style_login.css
  style_signup.css
Labels: 매운맛🔥

#98 [김도훈] sprint3
  Sprint-Mission1/css/style.css
  Sprint-Mission1/js/login.js
  Sprint-Mission1/js/signup.js
  Sprint-Mission1/login.html
  Sprint-Mission1/signup.html
Labels: 매운맛🔥

#109 [조영선] Sprint3
  Component 2.png
  Component 3.png
  Group (1).png
  Group.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  Vector.png
  btn_visibility_off_24px.png
  ic_instagram.png
  login.css
  login.html
  mission1-2.css
  mission1-2.html
  mission1-3.css
  mission1-3.html
  signup.css
  signup.html
  판다 얼굴.png
  판다마켓.png
Labels: 미완성🫠

#105 [우재현] Sprint3
  index.html
  public/css/index.css
  public/css/login.css
  public/css/style.css
  public/images/icon/social_google.png
  public/images/icon/social_kakao.png
  public/images/meta_thumbnail.png
  public/images/result_capture/basic_sprint3_landing_mobile_viewport.png
  public/images/result_capture/basic_sprint3_landing_tablet_viewport.png
  public/images/result_capture/basic_sprint3_login_mobile_viewport.png
  public/images/result_capture/basic_sprint3_signup_mobile_viewport.png
  public/images/result_capture/meta_debug.png
  public/js/login.js
  public/js/signup.js
  views/login.html
  views/signup.html
Labels: 매운맛🔥

#112 [홍지윤] sprint3
  desktop.ini
  text.txt
  코드잇 스프린트 미션 1/faq.html
  코드잇 스프린트 미션 1/image/contents/Img_home_01.png
  코드잇 스프린트 미션 1/image/contents/Img_home_02.png
  코드잇 스프린트 미션 1/image/contents/Img_home_03.png
  코드잇 스프린트 미션 1/image/contents/Img_home_bottom.png
  코드잇 스프린트 미션 1/image/contents/Img_home_top.png
  코드잇 스프린트 미션 1/image/logo/Property 1=sm.png
  코드잇 스프린트 미션 1/image/logo/favicon-16x16.png
  코드잇 스프린트 미션 1/image/sns/ic_facebook.png
  코드잇 스프린트 미션 1/image/sns/ic_instagram.png
  코드잇 스프린트 미션 1/image/sns/ic_twitter.png
  코드잇 스프린트 미션 1/image/sns/ic_youtube.png
  코드잇 스프린트 미션 1/index.css
  코드잇 스프린트 미션 1/index.html
  코드잇 스프린트 미션 1/items.html
  코드잇 스프린트 미션 1/login.html
  코드잇 스프린트 미션 1/privacy.html
  코드잇 스프린트 미션/home.html
  코드잇 스프린트 미션/image/logo/preview.png
  코드잇 스프린트 미션/login.html
  코드잇 스프린트 미션/signup.html
  코드잇 스프린트 미션/style/home.css
  코드잇 스프린트 미션/style/login.css
  코드잇 스프린트 미션/style/signup.css
Labels: 매운맛🔥, 미완성🫠

#96 박연학sprint4
  index.html
  login.html
  sign.js
  signup.html
  style/global.css
  style/home.css
  style/sign.css
Labels: 미완성🫠

#103 [정소망] sprint3
  img/meta.png
  index.html
  js/login.js
  js/signup.js
  login.html
  signup.html
  style/page/index.css
  style/page/index.css.map
  style/page/index.scss
  style/page/login.css
  style/page/login.css.map
  style/page/login.scss
  style/page/signup.css
  style/page/signup.css.map
  style/page/signup.scss
  style/setting/_fonts.scss
  style/setting/_vars.scss
  style/style.css
  style/style.css.map
Labels: 순한맛🐑

#97 [안형석] Sprint 3
  index.html
  landingpage/Img_home_01.png
  landingpage/Img_home_02.png
  landingpage/Img_home_03.png
  landingpage/Img_home_bottom.png
  landingpage/Img_home_top.png
  landingpage/img/landing/desktop_01.png
  landingpage/img/landing/desktop_02.png
  landingpage/img/landing/desktop_03.png
  landingpage/img/landing/desktop_04.png
  landingpage/img/landing/desktop_05.png
  landingpage/img/landing/mobile_01.png
  landingpage/img/landing/mobile_02.png
  landingpage/img/landing/mobile_03.png
  landingpage/img/landing/mobile_04.png
  landingpage/img/landing/mobile_05.png
  landingpage/img/landing/tablet_01.png
  landingpage/img/landing/tablet_02.png
  landingpage/img/landing/tablet_03.png
  landingpage/img/landing/tablet_04.png
  landingpage/img/landing/tablet_05.png
  sign-up.css
  style.css
Labels: 매운맛🔥

#107 [이학수] sprint3
  css/common.css
  css/login.css
  css/main.css
  img/common/og-image.png
  index.html
  js/chkRequired.js
  login.html
  readme.md
  signup.html
Labels: 매운맛🔥

#85 [박성우] sprint3
  auth.js
  font/Pretendard-Bold.otf
  font/Pretendard-Medium.otf
  font/Pretendard-Regular.otf
  font/Pretendard-SemiBold.otf
  font/ROKAF_Sans_Bold.ttf
  font/ROKAF_Sans_Medium.ttf
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/auth_logo.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_instagram.png
  img/ic_kakao.png
  img/ic_password0.svg
  img/ic_password1.svg
  img/ic_twitter.png
  img/ic_youtube.png
  img/main_1.jpg
  img/main_2.jpg
  img/main_3.jpg
  img/og_title.jpg
  img/pandalogo.jpg
  index.html
  index.js
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  pages/signup.html
  style/auth.css
  style/color.css
  style/fonts.css
  style/main.css
  style/reset.css
  style/style.css
Labels: 매운맛🔥

#120 [강수민] Sprint4
  js/auth.js
  js/login.js
  js/signup.js
  js/togglePwVisible.js
  js/validation.js
  pages/login.html
  pages/signin.html
  pages/signup.html
  style/auth.css
Labels: 매운맛🔥

#117 [우재현] Sprint4
  README.md
  public/css/login.css
  public/css/style.css
  public/images/result_capture/basic_sprint3_landing_mobile_viewport.png
  public/images/result_capture/basic_sprint3_landing_tablet_viewport.png
  public/images/result_capture/basic_sprint3_login_mobile_viewport.png
  public/images/result_capture/basic_sprint3_signup_mobile_viewport.png
  public/images/result_capture/basic_sprint4/login-input-empty.png
  public/images/result_capture/basic_sprint4/login-input-err1.png
  public/images/result_capture/basic_sprint4/login-input-valid.png
  public/images/result_capture/basic_sprint4/signup-input-err1.png
  public/images/result_capture/basic_sprint4/signup-input-valid.png
  public/images/result_capture/meta_debug.png
  public/js/login.js
  public/js/signup.js
  public/js/validation.js
  views/login.html
  views/signin.html
  views/signup.html
Labels: 매운맛🔥

#156 [오진화] sprint 4
  css/login.css
  images/google-icon.png
  images/kakao-icon.png
  images/판다 얼굴.png
  js/login.js
  js/validation.js
  login.html
  page/index.html
  page/items.html
  page/signup.html
Labels: 미완성🫠

#122 [최주영] Sprint4
  css/login.css
  js/form-utils/password-toggle.js
  js/form-utils/validation.js
  js/login.js
  js/signup.js
  login.html
  signup.html
Labels: 매운맛🔥

#113 [장수경] Sprint3
  home.css
  index.html
  sign.css
  signin.html
  signup.html
Labels: 매운맛🔥, 미완성🫠

#123 [이학수] sprint4
  css/common.css
  css/login.css
  faq.html
  img/login/ico-eye.png
  index.html
  items.html
  js/chkLoginForm.js
  js/chkRequired.js
  js/chkSignupForm.js
  js/utils.js
  login.html
  privacy.html
  signup.html
Labels: 매운맛🔥

#129 [이하림] Sprint 2
  .github/pull_request_template.md
  Sprint1.html
  default.css
  faq.html
  img/landing_page/img/landing/facebook-logo.png
  img/landing_page/img/landing/instagram-logo.png
  img/landing_page/img/landing/twitter-logo.png
  img/landing_page/img/landing/youtube-logo.png
  index.html
  items.html
  privacy.html
  signin.html
Labels: 미완성🫠, 순한맛🐑

#154 [김승준] Sprint4
  .github/sprint4/faq.html
  .github/sprint4/images/home/bottom-banner-image.png
  .github/sprint4/images/home/feature1-image.png
  .github/sprint4/images/home/feature2-image.png
  .github/sprint4/images/home/feature3-image.png
  .github/sprint4/images/home/hero-image.png
  .github/sprint4/images/icons/eye-invisible.svg
  .github/sprint4/images/icons/eye-visible.svg
  .github/sprint4/images/logo/favicon.ico
  .github/sprint4/images/logo/logo.svg
  .github/sprint4/images/logo/og-image.png
  .github/sprint4/images/social/facebook-logo.svg
  .github/sprint4/images/social/google-logo.png
  .github/sprint4/images/social/instagram-logo.svg
  .github/sprint4/images/social/kakao-logo.png
  .github/sprint4/images/social/twitter-logo.svg
  .github/sprint4/images/social/youtube-logo.svg
  .github/sprint4/index.html
  .github/sprint4/items.html
  .github/sprint4/privacy.html
  .github/sprint4/sign_utils.js
  .github/sprint4/signin.html
  .github/sprint4/signin.js
  .github/sprint4/signup.html
  .github/sprint4/signup.js
  .github/sprint4/styles/auth.css
  .github/sprint4/styles/global.css
  .github/sprint4/styles/home.css
Labels: 매운맛🔥

#144 [민지이] Sprint4
  .DS_Store
  img/ic_visibility_off.png
  img/ic_visibility_on.png
  index.css
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
Labels: 매운맛🔥

#142 [서현우] Sprint4
  .gitignore
  img/btn_large.png
  img/btn_small_48.png
  img/icon-google.png
  img/icon-kakao.png
  img/icon-password.close.png
  img/icon-password.open.png
  img/pandaface.png
  img/property1-lg.png
  img/©codeit - 2024.png
  index.html
  login.html
  login.js
  main.css
  signup.html
  signup.js
Labels: 매운맛🔥, 미완성🫠

#130 [윤예지] Sprint 4
  css/auth.css
  index.html
  js/auth/login.js
  js/auth/signup.js
  js/validation.js
  pages/auth/login.html
  pages/auth/signup.html
  pages/login.html
  pages/signin.html
  pages/signup.html
Labels: 매운맛🔥

#143 [석지우] Sprint4
  img/input-icon/eye-on.png
  img/meta/landing.png
  index.html
  login.html
  login.js
  loginStyle.css
  signup.html
  signup.js
  signupStyle.css
Labels: 매운맛🔥

#152 [한승지] sprint4
  pages/login/login.css
  pages/login/login.html
  pages/login/login.js
Labels: 매운맛🔥, 미완성🫠
