Repository codeit-bootcamp-frontend/11-Sprint-Mission, pull requests merged in 2024-11, with the labels that each got.

#255 [이준희] Sprint8
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api.tsx
  src/axiosInstance.tsx
  src/components/AddItemForm.tsx
  src/components/AllItem.tsx
  src/components/AllItemCard.tsx
  src/components/BestItem.tsx
  src/components/BestItemCard.tsx
  src/components/FileInput.css
  src/components/FileInput.tsx
  src/components/ItemComment.tsx
  src/components/ItemDetailForm.tsx
  src/components/Nav.tsx
  src/components/Pagination.tsx
  src/declarations.d.ts
  src/hooks/useAsync.tsx
  src/index.tsx
  src/layout.tsx
  src/pages/AddItem.tsx
  src/pages/ItemDetail.tsx
  src/pages/Items.tsx
  src/types.ts
  tsconfig.json
Labels: 매운맛🔥

#269 [우재현] Sprint8
  .env
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/api.js
  src/api.ts
  src/components/BestItemList/BestItemList.tsx
  src/components/CommentForm/CommentForm.tsx
  src/components/FileInput/FileInput.tsx
  src/components/ItemDetail/ItemDetail.tsx
  src/components/ItemList/ItemList.tsx
  src/components/ListItem/ListItem.css
  src/components/ListItem/ListItem.tsx
  src/components/Pagination/Pagination.tsx
  src/contexts/DeviceTypeContext.tsx
  src/hooks/useAsync.js
  src/index.js
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.tsx
  src/pages/ItemDetailPage/ItemDetailPage.tsx
  src/pages/ItemListPage/ItemListPage.tsx
  src/react-app-env.d.ts
  src/types/Comment.ts
  src/types/Product.ts
  tsconfig.json
Labels: 매운맛🔥

#262 [석지우] Sprint8
  package-lock.json
  package.json
  src/App.tsx
  src/Layout.tsx
  src/components/BestProduct.tsx
  src/components/Header.tsx
  src/components/Pagination.tsx
  src/components/ProductDetail/ProductDetailComment.js
  src/components/ProductDetail/ProductDetailComment.tsx
  src/components/ProductDetail/ProductDetailInput.tsx
  src/components/ProductList.tsx
  src/components/additem/AddProductInput.tsx
  src/components/additem/AdditemButton.tsx
  src/components/additem/ImageUpload.tsx
  src/hooks/api.js
  src/hooks/api.ts
  src/index.js
  src/pages/ProductDetail.js
  src/pages/ProductDetail.tsx
  src/pages/additem.tsx
  src/pages/items.tsx
  svg.d.ts
  tsconfig.json
Labels: 매운맛🔥

#267 [이학수] Sprint8
  .eslintrc.js
  .gitignore
  .prettierrc
  .vscode/settings.json
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/robots.txt
  src/App.js
  src/App.tsx
  src/Components/AllProducts.tsx
  src/Components/BestProducts.tsx
  src/Components/Comments.tsx
  src/Components/Dropdown.tsx
  src/Components/FileInput.tsx
  src/Components/Header.tsx
  src/Components/Img.tsx
  src/Components/Loading.tsx
  src/Components/Meta.tsx
  src/Components/Pagination.tsx
  src/Components/Product.tsx
  src/Components/Tag.tsx
  src/Main.js
  src/Pages/AddItem.page.tsx
  src/Pages/Home.jsx
  src/Pages/Item.page.tsx
  src/Pages/Items.js
  src/Pages/Items.page.tsx
  src/api/api.ts
  src/hooks/useAsync.ts
  src/index.css
  src/index.tsx
  src/info.js
  src/pages/Home.page.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/types.ts
  src/utils.ts
  src/utils/utils.js
  tailwind.config.js
  tsconfig.json
Labels: 미완성🫠

#260 [박연학] Sprint7
  src/App.js
  src/api/itemsApi.js
  src/components/Navbar.css
  src/components/Navbar.jsx
  src/images/icons/commentDefault.svg
  src/images/icons/commentEmpty.svg
  src/images/icons/ic_back.svg
  src/images/icons/more.svg
  src/images/icons/plusimg.svg
  src/pages/AddItemPage/AddItemPage.css
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/AddItemPage/components/ImageUpload.jsx
  src/pages/AddItemPage/components/InputTag.jsx
  src/pages/ItemDetailPage/ItemDetailPage.css
  src/pages/ItemDetailPage/ItemDetailPage.jsx
  src/pages/ItemDetailPage/components/ItemCommentForm.css
  src/pages/ItemDetailPage/components/ItemCommentForm.jsx
  src/pages/ItemDetailPage/components/ItemCommentList.css
  src/pages/ItemDetailPage/components/ItemCommentList.jsx
  src/pages/ItemDetailPage/components/ItemInfo.css
  src/pages/ItemDetailPage/components/ItemInfo.jsx
  src/pages/ItemDetailPage/components/MoreDropDown.css
  src/pages/ItemDetailPage/components/MoreDropDown.jsx
  src/pages/ItemPage/components/ProductCard.jsx
Labels: 매운맛🔥

#256 [김진희] Sprint 8
  package-lock.json
  package.json
  src/EntirePath.tsx
  src/Main.js
  src/api/api.ts
  src/components/App.js
  src/components/App.tsx
  src/components/BestProducts.tsx
  src/components/Comment.tsx
  src/components/Comments.js
  src/components/Comments.tsx
  src/components/EditMessage.js
  src/components/EditMessage.tsx
  src/components/EntireProducts.tsx
  src/components/FileInput.css
  src/components/FileInput.js
  src/components/FileInput.tsx
  src/components/ItemDetail.tsx
  src/components/Nav.tsx
  src/components/PageButton.js
  src/components/PageButton.tsx
  src/components/ProductsCategory.js
  src/components/ProductsCategory.tsx
  src/components/SearchBar.css
  src/components/SearchBar.js
  src/components/SelectBox.css
  src/components/SelectBox.tsx
  src/components/SmallButton.js
  src/components/SmallButton.tsx
  src/components/Tag.tsx
  src/index.js
  src/index.tsx
  src/pages/AddItemPage.tsx
  src/pages/HomePage.tsx
  src/pages/ItemDetailPage.tsx
  src/pages/ItemsPage.js
  src/pages/ItemsPage.tsx
  src/utils/custom.d.ts
  src/utils/reportWebVitals.ts
  tsconfig.json
Labels: 매운맛🔥

#268 [홍지윤] sprint7
  src/App.js
  src/api/ProductAPI.js
  src/components/CommentForm.css
  src/components/CommentForm.js
  src/components/CommentList.css
  src/components/CommentList.js
  src/components/ProductCard.css
  src/components/ProductCard.js
  src/components/ProductComment.css
  src/components/ProductComment.js
  src/components/ProductDetail.css
  src/components/ProductDetail.js
  src/components/UserProfile.css
  src/components/UserProfile.js
  src/image/heart-img.png
  src/image/user-avatar.png
  src/pages/Additem.js
  src/pages/ItemDetailPage.js
  src/styles/ItemDetailPage.css
  src/styles/Reset.css
Labels: 매운맛🔥

#266 [이동훈] Sprint7
  public/images/icons/ic_back.svg
  src/api/commentsApi.js
  src/api/productsApi.js
  src/components/pages/additem/AddItemTag.jsx
  src/components/pages/items/CommentBox.css
  src/components/pages/items/CommentBox.jsx
  src/components/pages/items/ItemsPage.jsx
  src/components/pages/items/KebabMenu.css
  src/components/pages/items/KebabMenu.jsx
  src/components/pages/items/ProductDetail.css
  src/components/pages/items/ProductDetail.jsx
  src/styles/shared.css
  src/utills.js
Labels: 매운맛🔥

#272 [한정빈] Sprint6
  craco.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/components/DeleteBtn.jsx
  src/components/Header.jsx
  src/images/ic_X.svg
  src/images/ic_plus.svg
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/AddItemPage/ItemContent.jsx
  src/pages/AddItemPage/ItemImage.jsx
  src/pages/AddItemPage/RegisterBtn.jsx
  src/pages/AddItemPage/TagList.jsx
  src/pages/AuthPage/LoginPage.jsx
  src/pages/AuthPage/SignUpPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ItemsPage/AllProducts.css
  src/pages/ItemsPage/AllProducts.jsx
  src/pages/ItemsPage/BestProducts.css
  src/pages/ItemsPage/BestProducts.jsx
  src/pages/ItemsPage/ItemsPage.jsx
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: 매운맛🔥

#258 [김도훈] Sprint8
  sprint-mission5/package-lock.json
  sprint-mission5/package.json
  sprint-mission5/src/App.tsx
  sprint-mission5/src/api/api.ts
  sprint-mission5/src/components/Allitem.tsx
  sprint-mission5/src/components/BestItem.jsx
  sprint-mission5/src/components/BestItem.tsx
  sprint-mission5/src/components/DetailContact.tsx
  sprint-mission5/src/components/DetailTop.tsx
  sprint-mission5/src/components/DropDownbtn.tsx
  sprint-mission5/src/components/Header.tsx
  sprint-mission5/src/components/ImageUpload.tsx
  sprint-mission5/src/components/ItemComments.tsx
  sprint-mission5/src/components/ItemList.tsx
  sprint-mission5/src/components/ItemSubmit.tsx
  sprint-mission5/src/components/OwnerFlexBox.tsx
  sprint-mission5/src/components/Pagination.tsx
  sprint-mission5/src/components/ProductDescription.tsx
  sprint-mission5/src/components/ProductName.tsx
  sprint-mission5/src/components/ProductPrice.tsx
  sprint-mission5/src/components/ReturnBtn.tsx
  sprint-mission5/src/components/Searchbox.tsx
  sprint-mission5/src/components/TagBar.tsx
  sprint-mission5/src/custom.d.ts
  sprint-mission5/src/hooks/UseDebouceSize.tsx
  sprint-mission5/src/page/Additem.jsx
  sprint-mission5/src/page/Additem.tsx
  sprint-mission5/src/page/DetailItem.tsx
  sprint-mission5/src/page/FreeBoard.jsx
  sprint-mission5/src/page/FreeBoard.tsx
  sprint-mission5/src/page/ItemCotainer.jsx
  sprint-mission5/src/page/ItemCotainer.tsx
  sprint-mission5/src/page/Mainpage.jsx
  sprint-mission5/src/page/Mainpage.tsx
  sprint-mission5/src/styles/device.ts
  sprint-mission5/src/types/type.ts
  sprint-mission5/tsconfig.json
Labels: 매운맛🔥

#277 [이준희] Sprint9
  components/AllArticles.tsx
  components/BestArticles.tsx
  components/Nav.tsx
  lib/api.tsx
  lib/axiosInstance.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/articles/[articleId].tsx
  pages/boards.tsx
  pages/index.tsx
  public/favicon.ico
  public/next.svg
  public/pngs/noImage.png
  public/svgs/Frame 2609463.svg
  public/svgs/ic_heart (1).svg
  public/svgs/ic_medal.svg
  public/svgs/ic_search.svg
  public/svgs/판다 얼굴.svg
  public/svgs/판다마켓.svg
  public/vercel.svg
  styles/Home.module.css
  styles/Nav.css
  styles/board.module.css
  styles/globals.css
  types/commontypes.ts
Labels: 매운맛🔥

#280 [김진희] sprint 9
  components/BestBoard.jsx
  components/EntireBoard.jsx
  components/Header.jsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/_app.tsx
  pages/_document.tsx
  pages/api/api.js
  pages/api/hello.ts
  pages/boards.jsx
  pages/index.tsx
  public/favicon.ico
  public/ic_heart.svg
  public/ic_login.svg
  public/ic_logo.svg
  public/ic_medal.svg
  public/ic_profile.svg
  public/ic_search.svg
  public/img_example.svg
  public/next.svg
  public/vercel.svg
  styles/BestBoard.module.css
  styles/Boards.module.css
  styles/EntireBoard.module.css
  styles/Header.module.css
  styles/globals.css
  tsconfig.json
Labels: 매운맛🔥

#294 [이학수] sprint9
  .gitignore
  .prettierrc
  README.md
  components/Footer/Footer.module.css
  components/Footer/ico-facebook.svg
  components/Footer/ico-instagram.svg
  components/Footer/ico-twitter.svg
  components/Footer/ico-youtube.svg
  components/Footer/index.tsx
  components/Img/index.tsx
  components/Nav/Nav.module.css
  components/Nav/index.tsx
  components/Nav/logo.svg
  components/Nav/txt-panda.svg
  lib/api.ts
  lib/formatDate.ts
  lib/formatMaxCount.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/boards/[id].tsx
  pages/boards/index.tsx
  pages/faq.tsx
  pages/index.tsx
  pages/items.tsx
  pages/login.tsx
  postcss.config.js
  public/favicon.ico
  public/images/boards/ico-medal.svg
  public/images/common/base-thumbnail.svg
  public/images/common/ico-arrow-down.svg
  public/images/common/ico-heart.svg
  public/images/common/ico-search.svg
  public/images/common/no-image.svg
  public/images/favicon.svg
  public/images/main/bg-bottom.png
  public/images/main/bg-hero.png
  public/images/main/hot-item.png
  public/images/main/register.png
  public/images/main/search.png
  public/next.svg
  public/vercel.svg
  styles/Boards.module.css
  styles/Home.module.css
  styles/globals.css
  svgr.d.ts
  tailwind.config.ts
  tsconfig.json
  types/article.type.ts
Labels: 미완성🫠

#282 [신휘철]Sprint9
  .gitignore
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/boards/[id].tsx
  pages/boards/index.tsx
  pages/index.tsx
  pages/items/index.tsx
  pages/login/index.tsx
  public/_redirects
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/assets/boards/best_badge.svg
  src/assets/boards/heart_icon.svg
  src/assets/boards/searchInput_icon.svg
  src/assets/boards/select_icon-m.svg
  src/assets/boards/select_icon.svg
  src/assets/codeit.png
  src/assets/footer/facebook_icon.svg
  src/assets/footer/instagram_icon.svg
  src/assets/footer/twitter_icon.svg
  src/assets/footer/youtube_icon.svg
  src/assets/home/Img_home_01.svg
  src/assets/home/Img_home_02.svg
  src/assets/home/Img_home_03.svg
  src/assets/home/Img_home_bottom.svg
  src/assets/home/Img_home_top.svg
  src/assets/logo-m.svg
  src/assets/logo.svg
  src/components/boards/AllArticles.style.ts
  src/components/boards/AllArticles.tsx
  src/components/boards/BestArticles.style.ts
  src/components/boards/BestArticles.tsx
  src/components/boards/CustomSelect.style.ts
  src/components/boards/CustomSelect.tsx
  src/components/boards/ProductControl.style.ts
  src/components/boards/ProductControl.tsx
  src/components/boards/SearchInput.style.ts
  src/components/boards/SearchInput.tsx
  src/layouts/Button.style.ts
  src/layouts/Button.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.style.ts
  src/layouts/Header.tsx
  src/layouts/Logo.style.ts
  src/layouts/Logo.tsx
  src/layouts/Navigation.style.ts
  src/layouts/Navigation.tsx
  src/layouts/StyledInner.style.ts
  src/types.ts
  styles/Footer.css
  styles/Home.css
  styles/Home.module.css
  styles/globals.css
Labels: 매운맛🔥

#284 [이주훈] sprint8
  .github/pull_request_template.md
  .gitignore
  declarations.d.ts
  package-lock.json
  package.json
  src/App.tsx
  src/api/itemApi.js
  src/assets/images/icons/Img_inquiry_empty.svg
  src/assets/images/icons/ic_add.svg
  src/assets/images/icons/ic_back.svg
  src/assets/images/icons/ic_del.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_profile.svg
  src/components/Header.tsx
  src/index.tsx
  src/pages/AddItemPage/AddItemPage.tsx
  src/pages/AddItemPage/component/ImgUpload.tsx
  src/pages/AddItemPage/component/InputItem.tsx
  src/pages/AddItemPage/component/InputTag.tsx
  src/pages/CommunityPage/CommunityPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ItemPage/ItemPage.tsx
  src/pages/ItemPage/component/CommentList.tsx
  src/pages/ItemPage/component/ItemComment.tsx
  src/pages/ItemPage/component/ItemProfile.tsx
  src/pages/ItemPage/component/LikeBtn.tsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MarketPage/MarketPage.tsx
  src/pages/MarketPage/component/AllItemsSection.tsx
  src/pages/MarketPage/component/BestItemsSection.tsx
  src/pages/MarketPage/component/DropDownList.tsx
  src/pages/MarketPage/component/ItemCard.tsx
  src/pages/MarketPage/component/Pagination.tsx
  src/utils/TimestampCal.tsx
  tsconfig.json
Labels: 매운맛🔥

#278 [박연학] sprint8
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/BeforeSprintReact/sign.js
  src/BeforeSprintReact/sign.ts
  src/api/itemsApi.ts
  src/components/DeleteButton.tsx
  src/components/Navbar.tsx
  src/custom.d.ts
  src/index.tsx
  src/pages/AddItemPage/AddItemPage.tsx
  src/pages/AddItemPage/components/ImageUpload.tsx
  src/pages/AddItemPage/components/InputField.tsx
  src/pages/AddItemPage/components/InputTag.tsx
  src/pages/ItemDetailPage/ItemDetailPage.tsx
  src/pages/ItemDetailPage/components/ItemCommentForm.tsx
  src/pages/ItemDetailPage/components/ItemCommentList.tsx
  src/pages/ItemDetailPage/components/ItemInfo.tsx
  src/pages/ItemDetailPage/components/MoreDropDown.tsx
  src/pages/ItemPage/ItemPage.tsx
  src/pages/ItemPage/components/AllProducts.tsx
  src/pages/ItemPage/components/BestProducts.tsx
  src/pages/ItemPage/components/DropDown.tsx
  src/pages/ItemPage/components/ProductCard.tsx
  tsconfig.json
Labels: 매운맛🔥

#287 [김도훈] Sprint9
  .eslintrc.json
  README.md
  my-app/.eslintrc.json
  my-app/.gitignore
  my-app/README.md
  my-app/next.config.ts
  my-app/package-lock.json
  my-app/package.json
  my-app/postcss.config.mjs
  my-app/public/head/logo_face.png
  my-app/public/head/logo_txt.png
  my-app/public/head/myPageIcon.png
  my-app/public/icon/best_icon.png
  my-app/public/icon/down_icon.png
  my-app/public/icon/drop_down_icon.png
  my-app/public/icon/like_icon.png
  my-app/public/icon/search_icon.png
  my-app/src/app/boards/page.tsx
  my-app/src/app/components/AllItem.tsx
  my-app/src/app/components/BestItem.tsx
  my-app/src/app/components/Header.tsx
  my-app/src/app/components/SearchBar.tsx
  my-app/src/app/fonts/PretendardVariable.woff2
  my-app/src/app/globals.css
  my-app/src/app/layout.tsx
  my-app/src/app/page.tsx
  my-app/src/app/type.tsx
  my-app/tailwind.config.ts
  my-app/tsconfig.json
  next.config.js
  package-lock.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
Labels: 매운맛🔥

#298 [김성종] Sprint9
  assets/images/home/bottom-banner-image.png
  assets/images/home/feature1-image.png
  assets/images/home/feature2-image.png
  assets/images/home/feature3-image.png
  assets/images/home/hero-image.png
  assets/images/icons/arrow_left.svg
  assets/images/icons/arrow_right.svg
  assets/images/icons/eye-invisible.svg
  assets/images/icons/eye-visible.svg
  assets/images/icons/ic_back.svg
  assets/images/icons/ic_heart.svg
  assets/images/icons/ic_kebab.svg
  assets/images/icons/ic_plus.svg
  assets/images/icons/ic_search.svg
  assets/images/icons/ic_sort.svg
  assets/images/icons/ic_x.svg
  assets/images/logo/logo.svg
  assets/images/social/facebook-logo.svg
  assets/images/social/google-logo.png
  assets/images/social/instagram-logo.svg
  assets/images/social/kakao-logo.png
  assets/images/social/twitter-logo.svg
  assets/images/social/youtube-logo.svg
  assets/images/ui/empty-comments.svg
  assets/images/ui/ic_profile.svg
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/components/Header.tsx
  pages/index.tsx
  public/favicon.ico
  styles/CommonStyles.ts
  styles/theme.ts
Labels: 매운맛🔥, 미완성🫠

#297 [최주영] Sprint9
  .eslintrc.json
  .gitignore
  README.md
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/favicon.ico
  public/images/dropdown.png
  public/images/dropup.png
  public/images/like.png
  public/images/loading.png
  public/images/logo.svg
  public/images/medal.png
  public/images/noImage.jfif
  public/images/profile.png
  public/images/search.png
  public/images/warning.png
  public/index.html
  public/robots.txt
  src/AddItem.tsx
  src/Board.tsx
  src/Items.tsx
  src/Product.tsx
  src/app/api.ts
  src/app/board/page.tsx
  src/app/components/Dropdown.tsx
  src/app/components/Header.tsx
  src/app/globals.css
  src/app/hooks/useAsync.ts
  src/app/items/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/types/article.ts
  src/assets/Img_inquiry_empty.png
  src/assets/backArrow.png
  src/assets/edit.png
  src/assets/favoriteIcon.png
  src/assets/logo.png
  src/assets/next.png
  src/assets/prev.png
  src/component/App.tsx
  src/component/Header.tsx
  src/css/AddItem.css
  src/css/Items.css
  src/css/header.css
  src/css/product.module.css
  src/css/style.css
  src/index.tsx
  src/library/AddItem/FileInput.tsx
  src/library/items/Dropdown.tsx
  src/library/items/ItemList.tsx
  src/service/api.js
  tailwind.config.ts
  tsconfig.json
  types/declarations.d.ts
Labels: 매운맛🔥

#276 [윤예지] Sprint9
  .prettierrc
  api/axios.ts
  api/productApi.ts
  components/BestCard.module.css
  components/BestCard.tsx
  components/Card.module.css
  components/Card.tsx
  components/Header.module.css
  components/Header.tsx
  components/common/Button.module.css
  components/common/Button.tsx
  components/common/Dropdown.module.css
  components/common/Dropdown.tsx
  components/common/Layout.module.css
  components/common/Layout.tsx
  components/common/Search.module.css
  components/common/Search.tsx
  hooks/useResize.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/boards/[id].tsx
  pages/boards/index.tsx
  pages/index.tsx
  pages/posts.tsx
  public/favicon.ico
  public/ic_drowdown.svg
  public/ic_heart.svg
  public/ic_medal.svg
  public/ic_search.svg
  public/ic_sort.svg
  public/next.svg
  public/panda.svg
  public/profile.svg
  public/testImage.png
  public/vercel.svg
  styles/Board.module.css
  styles/Home.module.css
  styles/globals.css
  styles/reset.css
Labels: 매운맛🔥
